name: Scan for secrets with trufflehog

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 6"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: ./.github/workflows/scan-for-secrets.yml
    with:
      tool: trufflehog
